### ISSUE TITLE
[docker] Publish tagged images for new releases and tags

### ISSUE THREAD

**Issue by myedibleenso** [ml4ai/skema#228]
For ease of reference, project releases and pushed tags should trigger new image builds and tags.  This should be straightforward to achieve if we incorporate the `docker/metadata-action` action to our workflow. Doing so will mean that we can remove the `setup` step (and any associated `needs: setup` lines) in favor of the `docker/metadata-action`.  The following example shows the new steps for building, tagging, and publishing the `lumai/askem-skema-py` image:

```yaml
  - name: Tags for image
    id: tags
    uses: docker/metadata-action@v4
    with:
      images: lumai/askem-skema-py
      tags: |
        # minimal
        type=semver,pattern={{version}}
        # short commit hash
        type=sha

  - name: Build and push image
    uses: docker/build-push-action@v4
    with:
      context: .
      file: "Dockerfile.skema-py"
      platforms: linux/amd64
      push: ${{ github.event_name != 'pull_request' }}
      # references `tags` step in steps for current job
      tags: ${{ steps.tags.outputs.tags }}
```

Note that we'll also change our workflow trigger from ... 

https://github.com/ml4ai/skema/blob/10c4a1e7df992362eb7e987e21e1e147f925aa7f/.github/workflows/docker.yml#LL3C1-L8C1

... to the following:

```yaml
on:
  push:
    branches: [main]
    tags:
      - v**
  pull_request:
    branches: [main]
  release:
    types: [published]
```
