### ISSUE TITLE
[gromet] list required properties for each element in the data model

### ISSUE THREAD

**Issue by myedibleenso** [ml4ai/skema#278]
Looking at the [v0.1.7 OpenAPI specification for the gromet data model](https://ml4ai.github.io/automates-v2/gromet_FN_v0.1.7.html), it’s unclear which (if any) properties are required vs optional.  I think this is a point of confusion for consumers of gromet JSON, especially as the specification continues to evolve.

I suggest we begin explicitly listing the required properties for [each object in our data model](https://github.com/ml4ai/automates-v2/blob/master/docs/source/gromet_FN_v0.1.7.yaml).  As an example of what I mean, consider the following snippet:

```yaml
components:
  schemas:
    BuildInfo:
    type: object
    required:
      - name
    properties:
      name:
        type: string
        description: “The name of the app.”
        example: “my awesome app”
      version:
        type: string
        description: “Current version of the app.”
        example: “0.1.0-SNAPSHOT”
```

Note the `required` key.

As a concrete example, consider [the following python snippet](https://gist.github.com/myedibleenso/d311903b70863ddde01ca5998c780375#file-example-gromet-py-L1-L2):

```python
greet = lambda: print("howdy!")
greet()
```

Here is its gromet JSON: https://gist.github.com/myedibleenso/d311903b70863ddde01ca5998c780375#file-example-gromet-json

Notice how this `GrometFN` has only a subset of the properties defined in its data model:

```json
{
  "b": [
    {
      "function_type": "FUNCTION",
      "gromet_type": "GrometBoxFunction",
      "name": "greet"
    }
  ],
  "gromet_type": "GrometFN"
}
```
