### ISSUE TITLE
[matlab] Use a specific release of grammar and test cases

### ISSUE THREAD

**Issue by jastier** [ml4ai/skema#460]
We should choose version of the MATLAB grammar and test repo stick with those

- Choose the last major release that passes the grammar testing without errors or warnings
- Reduce possible issues caused by new releases possibly including bugs

**Comment by vincentraymond-ua** [comment]
@jastier - You should be able to modify the clone_url field in languages.yaml to pin the version to a certain tag/commit/release

**Comment by vincentraymond-ua** [comment]
@jastier - I'm submitting a PR today that will add the functionality to specify the commit sha you want to use in languages.yml. This will allows us to pin a particular version for tree-sitter parsers. 

``` YAML
fortran:
  tree_sitter_name: tree-sitter-fortran
  clone_url: https://github.com/stadelmanma/tree-sitter-fortran.git
  commit_sha: f73d473
  supports_comment_extraction: True
  supports_fn_extraction: True
  extensions:
    - .f
    - .F
    - .f90
    - .f95
    - .for
```

**Comment by jastier** [comment]
@vincentraymond-ua - Nice! I have updated the `languages.yaml` MATLAB entry accordingly:

``` YAML
matlab:
  tree_sitter_name: tree-sitter-matlab
  clone_url: https://github.com/acristoffers/tree-sitter-matlab.git
  commit_sha: 6071891
  supports_comment_extraction: True
  supports_fn_extraction: True
  extensions:
    - .m
```

This tree-sitter-matlab commit isn't even a month old.   I can update to later versions as they are released.
